name: Slack Notification

on:
  workflow_call:
    inputs:
      RUNNER:
        description: 'Runner for the workflow'
        required: false
        type: string
        default: ubuntu-latest
      slack_webhook_url:
        required: false
        type: string
        default: ''
      workflow_name:
        required: true
        type: string
      workflow_conclusion:
        required: true
        type: string
      workflow_run_id:
        required: true
        type: string
      pr_number:
        required: false
        type: string
        default: ''
      branch_name:
        required: false
        type: string
        default: ''

permissions: {}

jobs:
  notify-slack:
    name: Notify Slack on Failure / Cancel / Timeout
    runs-on: ${{ inputs.RUNNER }}
    permissions:
      contents: read
    env:
      SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url || secrets.SLACK_WEBHOOK_URL_FIXME }}
      WORKFLOW_NAME: ${{ inputs.inputs.workflow_name }}
      WORKFLOW_CONCLUSION: ${{ inputs.workflow_conclusion }}
      WORKFLOW_RUN_ID: ${{ inputs.workflow_run_id }}
      PR_NUMBER: ${{ inputs.pr_number }}
      BRANCH_NAME: ${{ inputs.branch_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Send Slack Notification
        run: |
          bash ./notify_slack.sh \
            --webhook="$SLACK_WEBHOOK_URL" \
            --workflow-name="$WORKFLOW_NAME" \
            --conclusion="$WORKFLOW_CONCLUSION" \
            --run-id="$WORKFLOW_RUN_ID" \
            --workflow-path="$WORKFLOW_PATH" \
            --pr-number="$PR_NUMBER" \
            --branch-name="$BRANCH_NAME"
